apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: uro8d1fft-go 
  janus-idp.io/tekton: uro8d1fft-go
  backstage.io/kubernetes-id: uro8d1fft-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: uro8d1fft-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  