apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: uro8d1fft-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: uro8d1fft-go 
  name: uro8d1fft-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: uro8d1fft-go 
